type Gender = '남' | '여';
type Role = 'war' | 'civil' | 'strategist' | 'royal' | 'support' | 'female' | 'tribal';
type OfficerData = {
  id: string;
  name: string;
  courtesyName: string;
  birthYear: number | null;
  deathYear: number | null;
  gender: Gender;
  force: string;
  city: string;
  activeFrom: number;
  activeTo: number;
  leadership: number;
  martial: number;
  intelligence: number;
  politics: number;
  charisma: number;
  traits: string[];
  relations: string[];
  portraitKey: string;
  fullBodyKey: string;
};

const PRESET: Record<Role, [number, number, number, number, number]> = {
  war: [79, 84, 59, 50, 69],
  civil: [55, 32, 83, 88, 76],
  strategist: [66, 38, 90, 83, 79],
  royal: [67, 49, 74, 80, 82],
  support: [64, 58, 70, 68, 71],
  female: [38, 27, 73, 72, 86],
  tribal: [76, 85, 55, 44, 72],
};

const E = (
  id: string,
  name: string,
  courtesyName: string,
  force: string,
  city: string,
  activeFrom: number,
  activeTo: number,
  role: Role,
  traits: string[] = [],
  relations: string[] = [],
  gender: Gender = '남',
  stats?: [number, number, number, number, number]
): OfficerData => {
  const value = stats ?? PRESET[role];
  return {
    id,
    name,
    courtesyName,
    birthYear: null,
    deathYear: null,
    gender,
    force,
    city,
    activeFrom,
    activeTo,
    leadership: value[0],
    martial: value[1],
    intelligence: value[2],
    politics: value[3],
    charisma: value[4],
    traits: traits.length ? traits : [role === 'female' ? '여성인물' : role === 'civil' ? '문관' : role === 'strategist' ? '모사' : role === 'tribal' ? '이민족' : '장수'],
    relations,
    portraitKey: id,
    fullBodyKey: `${id}-full`,
  };
};

export const EXTRA_OFFICERS_DATA: OfficerData[] = [
  E('diaochan','초선','','재야','luoyang',190,199,'female',['연환계','무희'],['왕윤','여포'],'여',[28,22,83,68,98]),
  E('daqiao','대교','','손책군','jianye',195,220,'female',['교씨자매','언니'],['손책','소교'],'여',[31,20,74,72,95]),
  E('xiaoqiao','소교','','손권군','chaisang',195,223,'female',['교씨자매','동생'],['주유','대교'],'여',[30,21,76,71,96]),
  E('sunshangxiang','손상향','','손권군','jianye',200,230,'female',['궁요희','무예'],['손권','유비'],'여',[66,82,69,58,91]),
  E('zhenji','견씨','','조조군','ye',196,221,'female',['미모','문학'],['원희','조비'],'여',[32,18,84,77,96]),
  E('huangyueying','황월영','','재야','xiangyang',200,234,'female',['기계','지략'],['제갈량'],'여',[45,31,94,86,82]),
  E('ganfuren','감부인','','유비군','xiaopei',184,210,'female',['인덕'],['유비'],'여'),
  E('mifuren','미부인','','유비군','xiapi',194,208,'female',['헌신'],['유비','미축'],'여'),
  E('bianfuren','변부인','','조조군','xuchang',184,230,'female',['현모','궁정'],['조조','조비'],'여',[34,18,82,89,91]),
  E('wuguotai','오국태','','손견군','jianye',184,220,'female',['강동명문'],['손견','손권'],'여'),
  E('empresshe','하태후','','후한 조정','luoyang',184,189,'female',['황실'],['하진','소제'],'여'),
  E('fushou','복수','','후한 조정','xuchang',190,214,'female',['황후'],['헌제'],'여',[30,15,80,84,88]),
  E('dongbai','동백','','동탁군','chang_an',189,192,'female',['동씨일족'],['동탁'],'여'),
  E('guonuwang','곽여왕','','위','xuchang',200,235,'female',['황후','정치'],['조비'],'여',[36,20,86,91,88]),
  E('caojie_f','조절','','후한 조정','xuchang',196,260,'female',['황후','황실'],['조조','헌제'],'여'),
  E('caohua_f','조화','','후한 조정','xuchang',200,225,'female',['황실'],['조조'],'여'),
  E('xinxianying','신헌영','','위','luoyang',210,269,'female',['통찰','명문'],['신비'],'여',[40,24,92,88,87]),
  E('zhangchunhua','장춘화','','위','luoyang',200,247,'female',['결단','사마씨'],['사마의','사마사'],'여',[54,47,88,85,86]),
  E('wangyuanji','왕원희','','위','luoyang',227,268,'female',['통찰','사마씨'],['사마소'],'여',[48,31,91,90,89]),
  E('bulianshi','보연사','','손권군','jianye',200,238,'female',['후궁','인망'],['손권'],'여',[33,19,78,83,92]),
  E('sunluban','손노반','','오','jianye',220,260,'female',['황실','정쟁'],['손권'],'여',[39,30,78,74,73]),
  E('sunluyu','손노육','','오','jianye',220,255,'female',['황실'],['손권'],'여'),
  E('panshu','반숙','','오','jianye',220,252,'female',['황후'],['손권'],'여'),
  E('mayunlu','마운록','','유비군','chengdu',200,240,'female',['연의계열','기병'],['마초','조운'],'여',[76,88,66,55,87]),
  E('lulingqi','여령기','','여포군','xiapi',190,220,'female',['연의계열','기병'],['여포'],'여',[78,91,63,48,84]),
  E('guanyinping','관은병','','촉','chengdu',210,250,'female',['연의계열','무예'],['관우'],'여',[74,86,68,60,85]),
  E('baosanniang','포삼랑','','촉','chengdu',210,250,'female',['민간전승','무예'],['관색'],'여',[72,87,61,52,83]),
  E('huaman','화만','','남중세력','jianning',220,255,'female',['연의계열','남중'],['맹획','축융'],'여',[73,86,62,49,84]),

  E('liushan','유선','공사','촉','chengdu',214,271,'royal',['황제'],['유비','제갈량']),
  E('guanxing','관흥','안국','촉','chengdu',214,234,'war',['관우의 아들'],['관우','장포']),
  E('zhangbao_shu','장포','','촉','chengdu',214,234,'war',['장비의 아들'],['장비','관흥']),
  E('jianyong','간옹','헌화','유비군','zhuo',184,221,'civil',['외교'],['유비']),
  E('sunqian','손건','공우','유비군','xiapi',194,215,'civil',['외교'],['유비']),
  E('mizhu','미축','자중','유비군','xiapi',194,221,'civil',['재정','호상'],['유비','미방']),
  E('mifang','미방','자방','유비군','xiapi',194,220,'support',['장군'],['미축','관우']),
  E('yiji','이적','기백','유표군','xiangyang',190,220,'civil',['외교'],['유비']),
  E('liuba','유파','자초','촉','chengdu',208,222,'civil',['재정','법제'],['유비']),
  E('huangquan','황권','공형','유장군','chengdu',194,240,'strategist',['군략'],['유비']),
  E('qiaozhou','초주','윤남','촉','chengdu',220,270,'civil',['학자'],['유선']),
  E('donghe','동화','유재','촉','chengdu',200,221,'civil',['청렴'],['제갈량']),
  E('mazhong_shu','마충','덕신','촉','jianning',214,249,'war',['남중경영'],['제갈량']),
  E('lihui','이회','덕앙','촉','jianning',214,231,'civil',['남중경영'],['제갈량']),
  E('chenzhen_shu','진진','효기','촉','chengdu',208,235,'civil',['외교'],['유비']),
  E('yanghong_shu','양홍','계휴','촉','chengdu',214,228,'civil',['정무'],['유비']),
  E('wanglian','왕련','문의','촉','chengdu',214,223,'civil',['염철'],['유비']),
  E('laimin','내민','경달','촉','chengdu',214,260,'civil',['학자'],['유선']),
  E('yinmo','윤묵','사잠','촉','chengdu',214,250,'civil',['학자'],['제갈량']),
  E('qinmi','진밀','자칙','촉','chengdu',214,226,'civil',['논객'],['유비']),
  E('huojun','곽준','중막','유비군','jiangling',208,216,'war',['가맹관수비'],['유비']),
  E('huoyi','곽익','소선','촉','yongan',220,270,'war',['남중수비'],['곽준']),
  E('zhangsong','장송','영년','유장군','chengdu',194,213,'strategist',['익주지도'],['법정','유비']),
  E('yanyan','엄안','','유장군','jiangzhou',194,225,'war',['노장'],['장비']),
  E('zhangren','장임','','유장군','chengdu',194,214,'war',['충절','궁술'],['유장']),
  E('wulan','오란','','유비군','hanzhong',208,218,'war',['장군'],['유비']),
  E('leitong','뇌동','','유비군','hanzhong',208,218,'war',['장군'],['유비']),
  E('lengbao','냉포','','유장군','chengdu',194,214,'war',['장군'],['유장']),
  E('dengxian','등현','','유장군','chengdu',194,214,'war',['장군'],['유장']),
  E('liugui','유괴','','유장군','chengdu',194,214,'support',['익주관료'],['유장']),

  E('caorui','조예','원중','위','luoyang',220,239,'royal',['황제'],['조비']),
  E('caofang','조방','난경','위','luoyang',227,254,'royal',['황제'],['조예']),
  E('caomao','조모','언사','위','luoyang',234,260,'royal',['황제'],['사마소']),
  E('caohuan','조환','경명','위','luoyang',234,265,'royal',['황제'],['사마소']),
  E('caozhi','조식','자건','조조군','xuchang',196,232,'civil',['문학','칠보시'],['조조','조비']),
  E('caochong','조충','창서','조조군','xuchang',196,208,'support',['신동'],['조조']),
  E('caoshuang','조상','소백','위','luoyang',227,249,'royal',['대장군'],['조진','사마의']),
  E('xiahoumao','하후무','자림','위','chang_an',220,250,'support',['황족'],['하후돈']),
  E('xiahouwei','하후위','계권','위','xuchang',215,250,'war',['하후씨'],['하후연']),
  E('xiahouhe','하후화','의권','위','luoyang',220,260,'civil',['하후씨'],['하후연']),
  E('xiahouxuan','하후현','태초','위','luoyang',227,254,'civil',['명사'],['조상']),
  E('wangshuang','왕쌍','자전','위','chang_an',220,228,'war',['맹장'],['조진']),
  E('zhuling','주령','문박','조조군','xuchang',190,230,'war',['숙장'],['조조']),
  E('hanhao','한호','원사','조조군','xuchang',190,215,'war',['둔전'],['하후돈']),
  E('shihuan','사환','공류','조조군','xuchang',190,209,'war',['장군'],['조조']),
  E('niujin','우금_우장군','','위','xiangyang',208,235,'war',['장군'],['조인']),
  E('luqian','여건','자각','조조군','taishan',190,230,'war',['태산수비'],['조조']),
  E('liufu','유복','원영','조조군','hefei',196,208,'civil',['합비경영'],['조조']),
  E('jiakui','가규','양도','위','xuchang',200,228,'civil',['정무','수비'],['조조']),
  E('chentai','진태','현백','위','tianshui',227,260,'strategist',['서방방위'],['진군']),
  E('wangji_wei','왕기','백여','위','luoyang',220,261,'war',['군략'],['사마의']),
  E('wangling','왕릉','언운','위','shouchun',200,251,'war',['회남'],['사마의']),
  E('huzun','호준','','위','tianshui',220,250,'war',['서방장군'],['사마의']),
  E('hulie','호열','현무','위','luoyang',227,270,'war',['장군'],['호준']),
  E('heyan','하안','평숙','위','luoyang',210,249,'civil',['현학'],['조상']),
  E('dengyang','등양','현무','위','luoyang',220,249,'civil',['조상당'],['조상']),
  E('huanfan','환범','원칙','위','luoyang',220,249,'strategist',['지낭'],['조상']),
  E('xinpi','신비','좌치','조조군','xuchang',190,235,'civil',['외교'],['원소','조조']),
  E('duji','두기','백후','조조군','hedong',190,224,'civil',['하동태수'],['조조']),
  E('chenjiao','진교','계필','조조군','xuchang',196,237,'civil',['정무'],['조조']),
  E('wuzhi','오질','계중','위','xuchang',200,230,'civil',['문관'],['조비']),

  E('sunyi','손익','숙필','손책군','danyang',194,204,'war',['손씨일족'],['손책']),
  E('sunkuang','손광','계좌','손견군','changsha',184,205,'support',['손씨일족'],['손견']),
  E('sunben','손분','백양','손견군','lujiang',184,210,'war',['손씨일족'],['손견']),
  E('sunfu','손보','국의','손책군','lujiang',194,215,'war',['손씨일족'],['손책']),
  E('sunjing','손정','유대','손견군','changsha',184,210,'support',['손씨일족'],['손견']),
  E('wujing','오경','','손견군','danyang',184,203,'war',['외척'],['손견']),
  E('zhuzhi','주치','군리','손권군','wu',184,224,'war',['숙장'],['손견']),
  E('ludai','여대','정공','오','jiaozhi',200,256,'war',['교주경영'],['손권']),
  E('panjun','반준','승명','오','wuling',208,239,'civil',['형주경영'],['손권']),
  E('zhugeke','제갈각','원손','오','jianye',220,253,'strategist',['권신'],['제갈근']),
  E('zhugerong','제갈융','숙장','오','jianye',227,253,'war',['제갈씨'],['제갈각']),
  E('lukang','육항','유절','오','jianye',234,274,'war',['명장','수비'],['육손']),
  E('sundeng','손등','자고','손권군','jianye',215,241,'royal',['태자'],['손권']),
  E('sunhuan','손환','숙무','손권군','jiangling',208,250,'war',['손씨일족'],['손권']),
  E('sunshao','손소','장서','오','jianye',200,242,'civil',['재상'],['손권']),
  E('shiyi_wu','시의','자우','오','jianye',200,245,'civil',['청렴'],['손권']),
  E('luotong','낙통','공서','손권군','jianye',200,228,'civil',['간언'],['손권']),
  E('sunjiao','손교','숙랑','손권군','jianye',200,219,'war',['손씨일족'],['손권']),
  E('sunyu','손유','중이','손권군','danyang',194,215,'war',['손씨일족'],['손권']),
  E('guzong','고종','','오','jianye',220,250,'civil',['고씨'],['고옹']),
  E('zhuju','주거','자범','오','jianye',220,250,'war',['장군'],['손권']),
  E('luji','육적','공기','손권군','wu',200,219,'civil',['학자'],['육손']),
  E('chengbing','정병','덕추','손권군','jiaozhi',200,230,'civil',['학자'],['손권']),
  E('zhangwen_wu','장온','혜서','손권군','jianye',208,230,'civil',['외교'],['손권']),
  E('xuezong','설종','경문','오','jianye',208,243,'civil',['학자'],['손권']),

  E('liru','이유','문우','동탁군','luoyang',189,192,'strategist',['모사'],['동탁']),
  E('xurong','서영','','동탁군','luoyang',189,192,'war',['장군'],['동탁']),
  E('huzhen','호진','문재','동탁군','luoyang',189,192,'war',['서량군'],['동탁']),
  E('dongmin','동민','숙영','동탁군','chang_an',189,192,'support',['동씨일족'],['동탁']),
  E('lisu','이숙','','동탁군','luoyang',189,192,'support',['설객'],['여포','동탁']),
  E('qinyilu','진의록','','여포군','xiapi',190,199,'support',['장군'],['여포']),
  E('caoxing','조성','','여포군','xiapi',190,199,'war',['궁술'],['여포']),
  E('haomeng','학맹','','여포군','xiapi',190,196,'war',['반란'],['여포']),
  E('chenglian','성렴','','여포군','xiapi',190,199,'war',['장군'],['여포']),
  E('gaogan','고간','원재','원소군','bingzhou',190,206,'war',['병주'],['원소']),
  E('lvkuang','여광','','원소군','ye',190,205,'war',['장군'],['원소']),
  E('lvxiang','여상','','원소군','ye',190,205,'war',['장군'],['원소']),
  E('hanmeng','한맹','','원소군','ye',190,201,'war',['장군'],['원소']),
  E('jiangyiqu','장기거','','원소군','ye',190,205,'war',['장군'],['원소']),
  E('chenji_yuanshu','진기','','원술군','shouchun',190,199,'war',['장군'],['원술']),
  E('lifeng_yuanshu','이풍','','원술군','shouchun',190,199,'war',['장군'],['원술']),
  E('lianggang','양강','','원술군','shouchun',190,199,'war',['장군'],['원술']),
  E('yuejiu','악취','','원술군','shouchun',190,199,'war',['장군'],['원술']),
  E('qiaorui','교유','','원술군','shouchun',190,197,'war',['장군'],['원술']),
  E('yanxiang','염상','','원술군','shouchun',190,199,'civil',['모사'],['원술']),
  E('zhangxun_yuanshu','장훈','','원술군','shouchun',190,199,'war',['대장'],['원술']),
  E('hanyin','한윤','','원술군','shouchun',190,197,'civil',['외교'],['원술']),
  E('kuailiang','괴량','자유','유표군','xiangyang',190,208,'strategist',['모사'],['유표','괴월']),
  E('kuaiyue','괴월','이도','유표군','xiangyang',190,214,'strategist',['모사'],['유표','괴량']),
  E('caimao','채모','덕규','유표군','xiangyang',190,208,'war',['수군'],['유표']),
  E('zhangyun_jing','장윤','','유표군','xiangyang',190,208,'war',['수군'],['채모']),
  E('huangzu','황조','','유표군','jiangxia',190,208,'war',['강하태수'],['유표']),
  E('sufei','소비','','유표군','jiangxia',190,210,'support',['수군'],['감녕']),
  E('wangcan','왕찬','중선','유표군','xiangyang',190,217,'civil',['건안칠자'],['조조']),
  E('hansong','한숭','덕고','유표군','xiangyang',190,220,'civil',['외교'],['유표']),
  E('chendeng','진등','원룡','도겸군','xiapi',184,200,'strategist',['서주명사'],['유비','조조']),
  E('chengui','진규','한유','도겸군','xiapi',184,200,'civil',['서주명사'],['진등']),
  E('caobao','조표','','도겸군','xiapi',184,196,'war',['서주장수'],['도겸']),
  E('liuyao','유요','정례','유요군','jianye',190,197,'royal',['양주목'],['손책']),
  E('yanbaihu','엄백호','','엄백호군','wu',190,200,'war',['오군호족'],['손책']),
  E('xugong','허공','','허공군','wu',190,200,'civil',['오군태수'],['손책']),
  E('shengxian','성헌','효장','재야','wu',190,205,'civil',['명사'],['손책']),
  E('zerong','착융','','도겸군','guangling',184,197,'support',['호족'],['도겸']),
  E('zhangying_liuyao','장영','','유요군','jianye',190,197,'war',['장군'],['유요']),
  E('fanneng','번능','','유요군','jianye',190,197,'war',['장군'],['유요']),
  E('yumi','우미','','유요군','jianye',190,197,'war',['장군'],['유요']),

  E('chengyuanzhi','정원지','','황건군','zhuo',184,184,'war',['황건장수'],['장각']),
  E('dengmao','등무','','황건군','zhuo',184,184,'war',['황건장수'],['정원지']),
  E('peiyuanshao','배원소','','황건 잔당','runan',184,201,'war',['황건잔당'],['주창']),
  E('zhoucang','주창','','유비군','jiangling',184,220,'war',['충의','호위'],['관우']),
  E('zhangmancheng','장만성','','황건군','wan',184,184,'war',['황건장수'],['장각']),
  E('zhaohong','조홍_황건','','황건군','wan',184,185,'war',['황건장수'],['장각']),
  E('hanzhong_yellow','한충','','황건군','wan',184,185,'war',['황건장수'],['장각']),
  E('sunzhong_yellow','손중','','황건군','runan',184,184,'war',['황건장수'],['장각']),
  E('buji_yellow','복기','','황건군','qingzhou',184,190,'war',['황건장수'],['장각']),
  E('guotai','곽태','','백파적','hedong',184,195,'war',['백파적'],[]),
  E('yangfeng','양봉','','백파군','hedong',190,198,'war',['백파적'],['헌제']),
  E('hanxian','한섬','','백파군','hedong',190,197,'war',['백파적'],[]),
  E('lile','이락','','백파군','hedong',190,197,'war',['백파적'],[]),
  E('hucai','호재','','백파군','hedong',190,197,'war',['백파적'],[]),
  E('mulu','목록대왕','','남중세력','jianning',220,240,'tribal',['맹수부대'],['맹획']),
  E('ahuinan','아회남','','남중세력','jianning',220,240,'tribal',['남중'],['맹획']),
  E('dongtuna','동도나','','남중세력','jianning',220,240,'tribal',['남중'],['맹획']),
  E('jinhuansanjie','금환삼결','','남중세력','jianning',220,240,'tribal',['남중'],['맹획']),
  E('wutugu','올돌골','','오과국','yunnan',220,240,'tribal',['등갑병'],['맹획']),
  E('dailaidongzhu','대래동주','','남중세력','jianning',220,240,'tribal',['남중'],['축융']),
  E('mangyachang','망아장','','남중세력','jianning',220,240,'tribal',['남중'],['맹획']),
  E('duosi','타사대왕','','남중세력','yunnan',220,240,'tribal',['독천'],['맹획']),
  E('ehuan','악환','','고정군','jianning',220,240,'tribal',['맹장'],['고정']),
  E('gaoding','고정','','남중세력','yuexi',220,225,'tribal',['월수태수'],['제갈량']),
  E('yongkai','옹개','','남중세력','jianning',220,225,'support',['반란'],['맹획']),
  E('zhubao','주포','','남중세력','jianning',220,225,'support',['반란'],['맹획']),
];
